name: Test Setup

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-setup:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Run setup.sh
      run: |
        chmod +x setup.sh
        ./setup.sh

    - name: Verify setup
      run: |
        ./tests/test_setup.sh

    - name: Run Docker container for testing
      run: |
        docker run --rm -v $(pwd):/workspace -w /workspace ubuntu:latest /bin/bash -c "chmod +x setup.sh && ./setup.sh && ./tests/test_setup.sh"
